//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTbl
    {
        public int ID { get; set; }
        public string CoachName { get; set; }
        public Nullable<int> Age { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> TrainingID { get; set; }
    
        public virtual TrainingTbl TrainingTbl { get; set; }
    }
}
